version: "3"
services:
  docs:
    build: "api-docs-service"
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    depends_on:
      - voucher
  voucher:
    build: "voucher-service"
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://db/voucher-service
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - docs
      - voucher




